<?php

namespace App\Http\Controllers;

use App\Models\Company;
use App\Models\ProblemLog;
use Illuminate\Http\Request;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
use PhpOffice\PhpSpreadsheet\Style\Fill;
use PhpOffice\PhpSpreadsheet\Style\Border;
use PhpOffice\PhpSpreadsheet\Style\Alignment;

class ProblemLogExportController extends Controller
{
    public function export(Request $request)
    {
        $user = auth()->user();

        $query = ProblemLog::with(['company', 'assignedEngineer', 'createdByUser'])
            ->orderByDesc('created_at');

        if (($user->role ?? null) === 'customer' && !empty($user->company_id)) {
            $query->where('company_id', $user->company_id);
        }

        if ($request->filled('search')) {
            $search = trim((string) $request->search);
            $query->where(function ($q) use ($search) {
                $q->where('title', 'like', "%{$search}%")
                  ->orWhere('description', 'like', "%{$search}%")
                  ->orWhere('ticket_number', 'like', "%{$search}%")
                  ->orWhere('engineer_name', 'like', "%{$search}%");
            });
        }

        if ($request->filled('priority')) {
            $query->where('priority', $request->priority);
        }

        if ($request->filled('company_id')) {
            $query->where('company_id', $request->company_id);
        }

        if ($request->filled('assigned_engineer_id')) {
            $query->where('assigned_engineer_id', $request->assigned_engineer_id);
        }

        if ($request->filled('date_from')) {
            $query->whereDate('created_at', '>=', $request->date_from);
        }

        if ($request->filled('date_to')) {
            $query->whereDate('created_at', '<=', $request->date_to);
        }

        $logs = $query->get();

        if ($request->filled('response_sla')) {
            $responseSla = $request->response_sla;
            $logs = $logs->filter(function ($log) use ($responseSla) {
                return method_exists($log, 'responseSlaStatus') && $log->responseSlaStatus() === $responseSla;
            })->values();
        }

        if ($request->filled('resolution_sla')) {
            $resolutionSla = $request->resolution_sla;
            $logs = $logs->filter(function ($log) use ($resolutionSla) {
                return method_exists($log, 'resolutionSlaStatus') && $log->resolutionSlaStatus() === $resolutionSla;
            })->values();
        }

        if ($request->filled('status')) {
            $status = $request->status;
            $logs = $logs->filter(function ($log) use ($status) {
                return ($log->status ?? null) === $status;
            })->values();
        }

        $spreadsheet = new Spreadsheet();
        $spreadsheet->removeSheetByIndex(0);

        $total = $logs->count();
        $open = $logs->where('status', 'open')->count();
        $progress = $logs->where('status', 'in_progress')->count();
        $closed = $logs->where('status', 'closed')->count();
        $closureRate = $total > 0 ? round(($closed / $total) * 100) : 0;

        $responseBreached = $logs->filter(fn($l) => method_exists($l, 'responseSlaStatus') && $l->responseSlaStatus() === 'breached')->count();
        $resolutionBreached = $logs->filter(fn($l) => method_exists($l, 'resolutionSlaStatus') && $l->resolutionSlaStatus() === 'breached')->count();

        // ----------------------------------------------------------
        // Summary Sheet
        // ----------------------------------------------------------
        $summary = $spreadsheet->createSheet();
        $summary->setTitle('Summary');

        $summary->mergeCells('A1:F1');
        $summary->setCellValue('A1', 'Problem Log Export');

        $summary->setCellValue('A2', 'Generated At');
        $summary->setCellValue('B2', now()->format('d M Y H:i:s'));
        $summary->setCellValue('A3', 'Generated By');
        $summary->setCellValue('B3', $user->name ?? '-');

        $summary->setCellValue('A5', 'Applied Filters');
        $summary->setCellValue('A6', 'Search');
        $summary->setCellValue('B6', $request->search ?: '-');
        $summary->setCellValue('A7', 'Status');
        $summary->setCellValue('B7', $request->status ?: '-');
        $summary->setCellValue('A8', 'Priority');
        $summary->setCellValue('B8', $request->priority ?: '-');
        $summary->setCellValue('A9', 'Company');
        $summary->setCellValue('B9', optional(Company::find($request->company_id))->name ?: '-');
        $summary->setCellValue('A10', 'Engineer');
        $summary->setCellValue('B10', optional(\App\Models\User::find($request->assigned_engineer_id))->name ?: '-');
        $summary->setCellValue('A11', 'Response SLA');
        $summary->setCellValue('B11', $request->response_sla ?: '-');
        $summary->setCellValue('A12', 'Resolution SLA');
        $summary->setCellValue('B12', $request->resolution_sla ?: '-');
        $summary->setCellValue('A13', 'Date From');
        $summary->setCellValue('B13', $request->date_from ?: '-');
        $summary->setCellValue('A14', 'Date To');
        $summary->setCellValue('B14', $request->date_to ?: '-');

        $summary->setCellValue('D5', 'KPI');
        $summary->setCellValue('D6', 'Total Tickets');
        $summary->setCellValue('E6', $total);
        $summary->setCellValue('D7', 'Open');
        $summary->setCellValue('E7', $open);
        $summary->setCellValue('D8', 'In Progress');
        $summary->setCellValue('E8', $progress);
        $summary->setCellValue('D9', 'Closed');
        $summary->setCellValue('E9', $closed);
        $summary->setCellValue('D10', 'Closure Rate');
        $summary->setCellValue('E10', $closureRate . '%');
        $summary->setCellValue('D11', 'Response SLA Breached');
        $summary->setCellValue('E11', $responseBreached);
        $summary->setCellValue('D12', 'Resolution SLA Breached');
        $summary->setCellValue('E12', $resolutionBreached);

        $summary->getStyle('A1:F1')->applyFromArray([
            'font' => ['bold' => true, 'size' => 16, 'color' => ['rgb' => 'FFFFFF']],
            'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => '1D4ED8']],
        ]);

        $summary->getStyle('A5:B14')->applyFromArray([
            'borders' => ['allBorders' => ['borderStyle' => Border::BORDER_THIN, 'color' => ['rgb' => 'D1D5DB']]],
        ]);
        $summary->getStyle('D5:E12')->applyFromArray([
            'borders' => ['allBorders' => ['borderStyle' => Border::BORDER_THIN, 'color' => ['rgb' => 'D1D5DB']]],
        ]);

        foreach (['A' => 18, 'B' => 28, 'D' => 22, 'E' => 18] as $col => $width) {
            $summary->getColumnDimension($col)->setWidth($width);
        }

        // ----------------------------------------------------------
        // Tickets Sheet
        // ----------------------------------------------------------
        $sheet = $spreadsheet->createSheet();
        $sheet->setTitle('Tickets');

        $headers = [
            'ID','Ticket Number','Title','Description','Status','Priority','Company','Engineer',
            'Created At','Acknowledged At','Closed At','Response SLA','Resolution SLA',
            'Response Time','Resolution Time','Created By','Close Note'
        ];

        $sheet->mergeCells('A1:Q1');
        $sheet->setCellValue('A1', 'Problem Log Export - Tickets');
        $sheet->fromArray($headers, null, 'A3');

        $row = 4;
        foreach ($logs as $log) {
            $responseSla = method_exists($log, 'responseSlaStatus') ? $log->responseSlaStatus() : '-';
            $resolutionSla = method_exists($log, 'resolutionSlaStatus') ? $log->resolutionSlaStatus() : '-';
            $responseTime = method_exists($log, 'responseDurationText') ? $log->responseDurationText() : '-';
            $resolutionTime = method_exists($log, 'resolutionDurationText') ? $log->resolutionDurationText() : '-';

            $sheet->fromArray([
                $log->id,
                $log->ticket_number ?: ('TICKET-' . $log->id),
                $log->title,
                $log->description,
                $log->status,
                $log->priority,
                optional($log->company)->name,
                optional($log->assignedEngineer)->name ?: $log->engineer_name,
                optional($log->created_at)?->format('d M Y H:i'),
                optional($log->acknowledged_at)?->format('d M Y H:i'),
                optional($log->closed_at)?->format('d M Y H:i'),
                $responseSla,
                $resolutionSla,
                $responseTime,
                $resolutionTime,
                optional($log->createdByUser)->name,
                $log->close_note,
            ], null, 'A' . $row);

            $statusCell = 'E' . $row;
            if ($log->status === 'open') {
                $sheet->getStyle($statusCell)->getFill()->setFillType(Fill::FILL_SOLID)->getStartColor()->setRGB('FEE2E2');
                $sheet->getStyle($statusCell)->getFont()->getColor()->setRGB('B91C1C');
            } elseif ($log->status === 'in_progress') {
                $sheet->getStyle($statusCell)->getFill()->setFillType(Fill::FILL_SOLID)->getStartColor()->setRGB('FEF3C7');
                $sheet->getStyle($statusCell)->getFont()->getColor()->setRGB('B45309');
            } else {
                $sheet->getStyle($statusCell)->getFill()->setFillType(Fill::FILL_SOLID)->getStartColor()->setRGB('DCFCE7');
                $sheet->getStyle($statusCell)->getFont()->getColor()->setRGB('15803D');
            }

            $priorityCell = 'F' . $row;
            if ($log->priority === 'high') {
                $sheet->getStyle($priorityCell)->getFill()->setFillType(Fill::FILL_SOLID)->getStartColor()->setRGB('FEE2E2');
                $sheet->getStyle($priorityCell)->getFont()->getColor()->setRGB('B91C1C');
            } elseif ($log->priority === 'medium') {
                $sheet->getStyle($priorityCell)->getFill()->setFillType(Fill::FILL_SOLID)->getStartColor()->setRGB('DBEAFE');
                $sheet->getStyle($priorityCell)->getFont()->getColor()->setRGB('1D4ED8');
            } else {
                $sheet->getStyle($priorityCell)->getFill()->setFillType(Fill::FILL_SOLID)->getStartColor()->setRGB('E5E7EB');
                $sheet->getStyle($priorityCell)->getFont()->getColor()->setRGB('374151');
            }

            foreach (['L' => $responseSla, 'M' => $resolutionSla] as $col => $value) {
                $cell = $col . $row;
                if ($value === 'breached') {
                    $sheet->getStyle($cell)->getFill()->setFillType(Fill::FILL_SOLID)->getStartColor()->setRGB('FEE2E2');
                    $sheet->getStyle($cell)->getFont()->getColor()->setRGB('B91C1C');
                } elseif ($value === 'ok') {
                    $sheet->getStyle($cell)->getFill()->setFillType(Fill::FILL_SOLID)->getStartColor()->setRGB('DCFCE7');
                    $sheet->getStyle($cell)->getFont()->getColor()->setRGB('15803D');
                }
            }

            $row++;
        }

        $lastRow = max(4, $row - 1);

        $sheet->getStyle('A1:Q1')->applyFromArray([
            'font' => ['bold' => true, 'size' => 16, 'color' => ['rgb' => 'FFFFFF']],
            'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => '1D4ED8']],
        ]);

        $sheet->getStyle('A3:Q3')->applyFromArray([
            'font' => ['bold' => true, 'color' => ['rgb' => 'FFFFFF']],
            'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => '0F172A']],
            'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER],
        ]);

        $sheet->getStyle('A3:Q' . $lastRow)->applyFromArray([
            'borders' => ['allBorders' => ['borderStyle' => Border::BORDER_THIN, 'color' => ['rgb' => 'E5E7EB']]],
            'alignment' => ['vertical' => Alignment::VERTICAL_TOP, 'wrapText' => true],
        ]);

        $widths = [
            'A' => 8, 'B' => 20, 'C' => 28, 'D' => 40, 'E' => 16, 'F' => 14, 'G' => 24, 'H' => 22,
            'I' => 20, 'J' => 20, 'K' => 20, 'L' => 16, 'M' => 16, 'N' => 16, 'O' => 16, 'P' => 20, 'Q' => 28,
        ];
        foreach ($widths as $col => $width) {
            $sheet->getColumnDimension($col)->setWidth($width);
        }

        $sheet->freezePane('A4');
        $sheet->setAutoFilter('A3:Q' . $lastRow);

        // ----------------------------------------------------------
        // SLA Breaches Sheet
        // ----------------------------------------------------------
        $breachSheet = $spreadsheet->createSheet();
        $breachSheet->setTitle('SLA Breaches');

        $breachSheet->fromArray([
            ['ID', 'Ticket Number', 'Title', 'Company', 'Status', 'Response SLA', 'Resolution SLA', 'Engineer', 'Created At']
        ], null, 'A1');

        $breachLogs = $logs->filter(function ($log) {
            return (method_exists($log, 'responseSlaStatus') && $log->responseSlaStatus() === 'breached')
                || (method_exists($log, 'resolutionSlaStatus') && $log->resolutionSlaStatus() === 'breached');
        })->values();

        $row = 2;
        foreach ($breachLogs as $log) {
            $breachSheet->fromArray([[
                $log->id,
                $log->ticket_number ?: ('TICKET-' . $log->id),
                $log->title,
                optional($log->company)->name,
                $log->status,
                method_exists($log, 'responseSlaStatus') ? $log->responseSlaStatus() : '-',
                method_exists($log, 'resolutionSlaStatus') ? $log->resolutionSlaStatus() : '-',
                optional($log->assignedEngineer)->name ?: $log->engineer_name,
                optional($log->created_at)?->format('d M Y H:i'),
            ]], null, 'A' . $row);
            $row++;
        }

        $breachSheet->getStyle('A1:I1')->applyFromArray([
            'font' => ['bold' => true, 'color' => ['rgb' => 'FFFFFF']],
            'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => 'B91C1C']],
        ]);

        foreach (range('A', 'I') as $col) {
            $breachSheet->getColumnDimension($col)->setWidth(20);
        }

        // ----------------------------------------------------------
        // Company Summary Sheet
        // ----------------------------------------------------------
        $companySheet = $spreadsheet->createSheet();
        $companySheet->setTitle('Company Summary');

        $companySheet->fromArray([
            ['Company', 'Total Tickets', 'Open', 'In Progress', 'Closed']
        ], null, 'A1');

        $companyGrouped = $logs->groupBy(fn($l) => optional($l->company)->name ?? 'Unknown');
        $row = 2;
        foreach ($companyGrouped as $name => $items) {
            $companySheet->fromArray([[
                $name,
                $items->count(),
                $items->where('status', 'open')->count(),
                $items->where('status', 'in_progress')->count(),
                $items->where('status', 'closed')->count(),
            ]], null, 'A' . $row);
            $row++;
        }

        $companySheet->getStyle('A1:E1')->applyFromArray([
            'font' => ['bold' => true, 'color' => ['rgb' => 'FFFFFF']],
            'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => '1D4ED8']],
        ]);

        foreach (['A' => 28, 'B' => 16, 'C' => 12, 'D' => 16, 'E' => 12] as $col => $width) {
            $companySheet->getColumnDimension($col)->setWidth($width);
        }

        // ----------------------------------------------------------
        // Engineer Summary Sheet
        // ----------------------------------------------------------
        $engineerSheet = $spreadsheet->createSheet();
        $engineerSheet->setTitle('Engineer Summary');

        $engineerSheet->fromArray([
            ['Engineer', 'Total Tickets', 'Open', 'In Progress', 'Closed']
        ], null, 'A1');

        $engineerGrouped = $logs->groupBy(fn($l) => optional($l->assignedEngineer)->name ?: $l->engineer_name ?: 'Unassigned');
        $row = 2;
        foreach ($engineerGrouped as $name => $items) {
            $engineerSheet->fromArray([[
                $name,
                $items->count(),
                $items->where('status', 'open')->count(),
                $items->where('status', 'in_progress')->count(),
                $items->where('status', 'closed')->count(),
            ]], null, 'A' . $row);
            $row++;
        }

        $engineerSheet->getStyle('A1:E1')->applyFromArray([
            'font' => ['bold' => true, 'color' => ['rgb' => 'FFFFFF']],
            'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => '0F766E']],
        ]);

        foreach (['A' => 28, 'B' => 16, 'C' => 12, 'D' => 16, 'E' => 12] as $col => $width) {
            $engineerSheet->getColumnDimension($col)->setWidth($width);
        }

        $spreadsheet->setActiveSheetIndex(0);

        $parts = ['problem-log-export'];
        if ($request->filled('status')) $parts[] = $request->status;
        if ($request->filled('priority')) $parts[] = $request->priority;
        if ($request->filled('date_from')) $parts[] = $request->date_from;
        if ($request->filled('date_to')) $parts[] = $request->date_to;
        $parts[] = now()->format('Y-m-d-His');

        $fileName = implode('-', $parts) . '.xlsx';
        $tempPath = storage_path('app/' . $fileName);

        $writer = new Xlsx($spreadsheet);
        $writer->save($tempPath);

        return response()->download($tempPath, $fileName)->deleteFileAfterSend(true);
    }
}
